name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      # https://github.com/actions/runner-images/issues/7506
      - name: Accept Android SDK license
        run: echo "y" | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0-rc3"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew :app:buildDebug

      - name: Test
        run: ./gradlew :app:test

      - name: Snapshot test
        id: snapshots
        run: ./gradlew :app:verifyPaparazziDebug

      - name: Report snapshot failures
        if: ${{ failure() && steps.snapshots.conclusion == 'failure' }}
        run: echo "TEST"

