name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Lint my-cyclist
        run: ./gradlew :app:spotlessCheck

      - name: Build my-cyclist
        run: ./gradlew :app:buildDebug -x test

      - name: Test my-cyclist
        run: ./gradlew :app:test
