name: record-snapshots

on:
  issue_comment:
    types: [created]

jobs:
  record-snapshots:
    name: Update snapshots
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/record-snapshots' }}
    runs-on: macos-14
    steps:
      - id: get-branch
        run: echo ::set-output name=branch::$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-branch.outputs.branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Remove old screenshots
        run: rm -rf app/src/test/snapshots

      - name: Snapshot test
        run: ./gradlew :app:recordPaparazziDebug

      - name: Update snapshots
        run: |
          git config --global user.email "patxi952@gmail.com"
          git config --global user.name "Patxi Bocos"
          git add app/src/test/snapshots/*
          git commit -m 'Update snapshots'
          git push
